name: Release
on:
  release:
    types:
      - released

jobs:
  publish-to-brew-tap:
    name: Publish to Brew Tap
    runs-on: ubuntu-latest
    steps:

      - name: Generate App Token
        uses: tibdex/github-app-token@v2
        id: generate_token
        with:
          private_key: ${{ secrets.WORKSOME_INTERNAL_PRIVATE_KEY }}
          app_id: ${{ secrets.WORKSOME_INTERNAL_APP_ID }}
          installation_retrieval_mode: repository
          installation_retrieval_payload: worksome/homebrew-tap

      - name: Get version
        id: version
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true # Strip 'v' prefix

      - name: Trigger Homebrew Tap Update
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Trigger Formula
          repo: worksome/homebrew-tap
          ref: main
          token: ${{ steps.generate_token.outputs.token }}
          inputs: |
            {
                "name": "graphlint",
                "version": "${{ steps.version.outputs.tag }}",
                "download-url": "https://github.com/worksome/graphlint/releases/download/${{ github.event.release.tag_name }}/graphlint"
            }
